sudo: required

language: node_js

node_js:
  - 16

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "wE5b1hehhHhEc4Lvf9TWNEy6t3RQPQqIbmlIgrLY4e80j20AI0z6CmwCg7AXAmY8BBvxSVb4BnZlnuVIZJpd8f3/zXE9sP2dEdP7cXA2crBh3dn6llzwU9dJEGu+izJGYP9IXi5eKNTh0V5yso/0X8HQeHDWpTSdauc3KSTQGxnB8IGO1Lno3sbaHLwmDtR4WUG2Q7s764NL2fluAKuQlZeY8VLzlGwQAOhDTohbqJlUWieHm2rkiJvB6lHxsKPmrT1BpS3mhYGL8tTPRJYWWqI6/k9R5nIlJgpGZb2YUq3tHlxkAjmiQrTgqeOcwpnFRdm/IG+KnjXkUzFc16fl/cGhJlmTJFnwPMWUKV0+rPX0ylDSz4i7ZwrRcznF7EWrEl+pXXly3hKJc+RxzwmAy5cUiohMrUjNWgu/rCLMK9S2V/eSG7WSS7FAb02Ri2DJ2f0t7fgUaYCuqVllV9q0mezfZp96q5iM1Ob0kpxZhOYOkIOBJWb8r9+69DouJNRm/L7GnvYDoqt2JRJJtwo63hGEWF+ZhK/v+R5HAujAsZChLikly/jMSE0BNR9i0Sks698Q+tOSiC0Jre2g7ZmTfbcs3nEDtof9zh9+aQcVQlyFUzzftVvPYxtmgIOIvIiLZAMx/1BFLGKVXy/g3swWlHYzgJq5VhIb0AKjbbC9wKo="
    # AWS_SECRET_ACCESS_KEY
    - secure: "WzAQdol1SClIyL366iYmn71w3JueArEiGxItocgN/7NuPlZVTRv2WxHwHTsCgZ1b+Q05jih0p8DQ06CRXORcKAx+WIRG/dAtRo0nBki1Qp7vWJNPQAKNYOVsGGwI77ojBwMQwNv8IG3c3zacHpgudfC1EhLihQF6yPVDjhHuvuALDmGzpm3l3OoGkuf9m/6ktIW/NRWCmZUdtSyr/bHj1gc4YM4QM85XEPXXI7RxD8/aQFJJN9z9wdLY9mPNgeKBH4bbAHgLxuF7XJb+Huj7GJ7bwLl7rDTm/myNuHfOtuyftxwXMLrc/3VeoHKY17meQ8wq87LtOrJQ+5s0VkykDyjWfnSlLjel8LuqBzkwzg6txELPGWlqv35EnsI1zRpZiOeYFLgyuHx+swMPtXX4SZQJUKWxePkBU+KbvItKlb+RWzIpLZ/6Y9nUu2mDbk+QxVDHfVh1HDrjrgebn6FlHFb/SF/GIIu0FhhK5+rG5NOVLdLk96Juf+JWL2mjdz7xYjtMXv4H+YZ5/KCtsLvXI953Xq6i2C5nE7QfeRPTA71Q9zL3NC7RKs3RKPbjCNOK0iDU1MwIaLhP/pZiVEmMiRgHv6WjN1g47+gLICinxXKMrOfP8Rj3lEkjUIT5lkfN2+9xh6+Wd0GlPs+XH3QsGibWtLFBiRBONVijU/8JYDo="

before_install:
  - npm i -g npm@6

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - npm ci

script:
  - npm run travis
  - cd oppija
  - export BASE_IMAGE=baseimage-fatjar-openjdk8:master
  - ../ci-tools/common/pull-image.sh
  - ./scripts/ci/build.sh ehoks-oppija-ui
  - cd ../virkailija
  - ./scripts/ci/build.sh ehoks-virkailija-ui
  - cd ../tyopaikantoimija
  - ./scripts/ci/build.sh ehoks-tyopaikantoimija-ui

deploy:
  provider: script
  script: >-
    ../ci-tools/build/upload-image.sh ehoks-oppija-ui &&
    ../ci-tools/build/upload-image.sh ehoks-virkailija-ui
    &&
    ../ci-tools/build/upload-image.sh ehoks-tyopaikantoimija-ui
  on:
    all_branches: true

cache:
  directories:
    - "$HOME/.npm"
