dist: trusty

sudo: required

language: node_js

node_js:
  - "10"

install:
  - npm i -g npm@6
  - npm ci

script:
  - npm run lint
  - npm test
  - npm run build

cache:
  directories:
    - "$HOME/.npm"

