sudo: required

language: node_js

node_js:
  - "10"

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "fH3WILgQNnwb9BK+rtb3e8SoBjXW/tDSFHIxF6oWAnLUt22iOwBpcC5chweIj7idX8CG1tzLTKnc+TnDvxkWqWfkXCQqCGMDhIdyAdrmb6H7jHhyd1PK7tQ7jdTgGKfwZxsXTODxWdvW+U7zX/siXoS+RCbRCuLQBGtweFzi0ePoLbouwjYV+sX0uMW2oNPp6lsBOZA7k1Y486iggtlFTGZSjOas3+In4M8UnKHJRiAKIRhx8KOgg/3kidCQkgDpvpV9RZ7LbJ0n98qisbcJtAlUBayTKWrt4IUaYDbIb/Yx5gP1Ry0HN9fCmwWYALO3yR7ELsQ4uAQq+4YpwRC32Xz7/1os8ZVkxmXt9ns0ajxOsMHlXkVDpfKAD0z9pggWYmsJNsAMzq95VHi6Vc25SEJqET5IInExF1HK9VkCEBolT/OYq1333+Y+yuh+svmYUddtyAM5cZw+GhFr7VfVbiwcG88Xgi5avZEU8acVBt4Vr7g+aJbLT9ks+W+flh8DRC/vLJJ7/pJpBHk4YDDY07LXA2+Onenpwhtrs0lx7qjSyPLPPSx4bfhOc7bnYbfpBanJ2HIBRy+xZYLk7xgSzhXfQqhnZtEKanxiFEVFRm0RuyXqGtUP/Go3g1/BdrGmWsC1g6Y4tJLmQ47JrV/dgCwA+OmTtEBCo+Kv8MirWwU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "T3p7wOOSSG25lJQxmubYAIofQQcrmBfUamSxKKSUPTSKAg9OFiRHxGwUsY7EMN1dKxJXzd4E0owypGUNluf0+tISCUn763HYVhPMYluuoRHclGNjdmKbi7V7mqftNBE4raDcMf2cz+elBx4GsMpL7BNY1RoDq9Z1b/8wcAS73Fm98KTkKoq5gONRPe1LZQw7B/MDzLCMOd+DGhazv17O5hBVKp4Xe7SVF644f8rg+5ICxa9rZ4NgdwFzlj7VIyrBUnp+Fj/JDZ93jSsMvK+dlEJwgAIycmqLzIdF0zKfKR9MwliGZ4zx2TWVmYaVHi7INthjIMoc7YeYo/b/L+KodCsisv5KteqJrK5XFUL0VrxRl19XfSnZr68ElEW5GHCVGRA16umoBchnmgBdsgqamLX+iW1UO8/1dqyi0G8+xdyx9XclaPE5RRxkHJ8MoFpyIlr2rU8ZiVOnDCcnR51q0XXSnkQM3/UV7gWbtAW6R/hZYmhCSEXOQMCuD8qy5QvgWRCd79uO8/E9LZ1/RxYnQFIflY/tYoC81E1JuhMgfUbVBm/G1UEgbeHSjoE6dcubH8845kfAIXtRADF9FnNBKL2NskRr3j4VEGYX+NaOfk3m6sOD7ZU2t1TrT8R8MPGWLRntZW3R5BmVrW0ncC+yNDQu3lbzfGOx3eJhZhFSWt8="

before_install:
  - npm i -g npm@6

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - npm ci

script:
  - npm run travis
  - cd oppija
  - export BASE_IMAGE=baseimage-fatjar-openjdk8:master
  - ../ci-tools/common/pull-image.sh
  - ./scripts/ci/build.sh ehoks-oppija-ui
  - cd ../virkailija
  - ./scripts/ci/build.sh ehoks-virkailija-ui
  - cd ../tyopaikantoimija
  - ./scripts/ci/build.sh ehoks-tyopaikantoimija-ui

deploy:
  provider: script
  script: >-
    ../ci-tools/build/upload-image.sh ehoks-oppija-ui &&
    ../ci-tools/build/upload-image.sh ehoks-virkailija-ui
    &&
    ../ci-tools/build/upload-image.sh ehoks-tyopaikantoimija-ui
  on:
    all_branches: true

cache:
  directories:
    - "$HOME/.npm"
